# Generated by Django 3.2.9 on 2021-11-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
        ('accounts', '0002_user_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(blank=True, to='pins.Topic'),
        ),
    ]
