# Generated by Django 3.2.9 on 2021-11-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_saved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='saved_by',
            new_name='saved_img',
        ),
    ]
